export enum ActionNames {
    GET_MESSAGES = 'GET_MESSAGES',
    ADD_MESSAGES = 'ADD_MESSAGES',
    SEND_MESSAGE = 'SEND_MESSAGE',

    CLEAR_STORE = 'CLEAR_STORE',

    LOGIN = 'LOGIN',
    LOGIN_FROM_STORE = 'LOGIN_FROM_STORE',

    SET_SESSION_INFO = 'SET_SESSION_INFO',
}
