export enum ActionNames {
    GET_CHATS = 'GET_CHATS',
    ADD_CHATS = 'ADD_CHATS',
    CREATE_CHAT = 'CREATE_CHAT',
    MODIFY_CHAT = 'MODIFY_CHAT',

    GET_MESSAGES = 'GET_MESSAGES',
    ADD_MESSAGES = 'ADD_MESSAGES',
    SEND_MESSAGE = 'SEND_MESSAGE',

    GET_USERS = 'GET_USERS',
    ADD_USERS = 'ADD_USERS',
    MODIFY_USER = 'MODIFY_USER',

    CLEAR_STORE = 'CLEAR_STORE',

    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    LOGIN_FROM_STORE = 'LOGIN_FROM_STORE',
    LOGOUT = 'LOGOUT',

    SET_SESSION_INFO = 'SET_SESSION_INFO',
    SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT',
    SET_DRAWER_IS_OPEN = 'SET_DRAWER_IS_OPEN',
    CHANGE_ACTIVE_CHAT = 'CHANGE_ACTIVE_CHAT',
    SET_ADD_CHAT_DIALOG_IS_OPEN = 'SET_ADD_CHAT_DIALOG_IS_OPEN',
    SET_MODIFY_CHAT_DIALOG_IS_OPEN = 'SET_MODIFY_CHAT_DIALOG_IS_OPEN',
    SET_MODIFY_USER_DIALOG_IS_OPEN = 'SET_MODIFY_USER_DIALOG_IS_OPEN',
}
