export enum ActionNames {
    CREATE_CHAT = 'CREATE_CHAT',
    MODIFY_CHAT = 'MODIFY_CHAT',

    GET_MESSAGES = 'GET_MESSAGES',
    ADD_MESSAGES = 'ADD_MESSAGES',
    SEND_MESSAGE = 'SEND_MESSAGE',

    CLEAR_STORE = 'CLEAR_STORE',

    LOGIN = 'LOGIN',
    REGISTER = 'REGISTER',
    LOGIN_FROM_STORE = 'LOGIN_FROM_STORE',
    LOGOUT = 'LOGOUT',

    SET_SESSION_INFO = 'SET_SESSION_INFO',
    SET_ACTIVE_CHAT = 'SET_ACTIVE_CHAT',
    SET_DRAWER_IS_OPEN = 'SET_DRAWER_IS_OPEN',
    CHANGE_ACTIVE_CHAT = 'CHANGE_ACTIVE_CHAT',
}
