export const GET_CHATS = 'GET_CHATS';
export const CHATS_ADD = 'CHATS_ADD';
export const CREATE_CHAT = 'CREATE_CHAT';
export const MODIFY_CHAT = 'MODIFY_CHAT';

export const GET_MESSAGES = 'GET_MESSAGES';
export const MESSAGES_ADD = 'MESSAGES_ADD';
export const SEND_MESSAGE = 'SEND_MESSAGE';

export const GET_USERS = 'GET_USERS';
export const USERS_ADD = 'USERS_ADD';
export const MODIFY_USER = 'MODIFY_USER';

export const STORE_CLEAR = 'STORE_CLEAR';

export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
export const LOGIN_FROM_STORE = 'LOGIN_FROM_STORE';
export const LOGOUT = 'LOGOUT';

export const SESSION_INFO_SET = 'SESSION_INFO_SET';
export const IS_LOGGED_IN_SET = 'IS_LOGGED_IN_SET';
export const ACTIVE_CHAT_SET = 'ACTIVE_CHAT_SET';
export const DRAWER_IS_OPEN_SET = 'DRAWER_IS_OPEN_SET';
export const CHANGE_ACTIVE_CHAT = 'CHANGE_ACTIVE_CHAT';
export const ADD_CHAT_DIALOG_IS_OPEN_SET = 'ADD_CHAT_DIALOG_IS_OPEN_SET';
export const MODIFY_CHAT_DIALOG_IS_OPEN_SET = 'MODIFY_CHAT_DIALOG_IS_OPEN_SET';
export const USER_MODIFY_DIALOG_IS_OPEN_SET = 'USER_MODIFY_DIALOG_IS_OPEN_SET';
