name: 'Test'

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        node: [12.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
        CI: true
    steps:
    - uses: actions/checkout@v1
    - name: 'Use Node.js ${{ matrix.node }}'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: 'Install dependencies'
      run: npm ci
    - name: 'ESLint'
      run: npm run lint
    - name: 'Build production build'
      run: npm run build
    - name: 'Run tests'
      run: npm test           